villes =[
    {
        nom:"Ariana",
        description:"L'Ariana est l'une des plus importantes villes de la banlieue de Tunis. La ville se trouve au nord de la capitale.",
        titre:"Ou aller à ariana",
        description2:"Dans notre exploration de la magnifique région d'Ariana, nous sommes impatients de vous présenter une sélection soigneusement choisie d'endroits exceptionnels à visiter",
        photo1 :"../ressources-map/ariana/escape-room.jpg",
        photo1_title:"Escape room",
        photo1_subtitle:"loisirs",
        photo1_description:"Explorez l'Ariana d'une manière unique en visitant notre escape room passionnante. Testez vos compétences et vivez une expérience divertissante qui ajoutera une touche mémorable à votre séjour",
        photo2: "../ressources-map/ariana/golf-de-carthage.jpg",
        photo2_title:"Golf de carthage",
        photo2_subtitle:"Golf Courses",
        photo2_description:"Situé à 10 km de l'aéroport de Tunis-Carthage et à quelques minutes du centre-ville de Tunis et de la zone touristique des côtes de Carthage, le parcours de golf de Carthage offre une expérience exceptionnelle",
        photo3: "../ressources-map/ariana/parc_enahli.jpg",
        photo3_title:"Parc Ennahli",
        photo3_subtitle:"Parcs",
        photo3_description:"Découvrez la tranquillité du Parc Ennahli à Ariana lors d'une agréable promenade. Profitez de la nature verdoyante et offrez-vous une escapade relaxante en plein air.",
        lien_youtube:"https://www.youtube.com/embed/3NYdAETs_pA?si=el7kOuTFKSui5Fws&amp;start=27",
        map_title:"Explorez Ariana à travers notre carte.",
        map_src:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d51070.32831232462!2d10.129160135657674!3d36.86891960708965!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12e2cb4e31471bf3%3A0x65bc5efbce842198!2sAriana!5e0!3m2!1sfr!2stn!4v1705766131826!5m2!1sfr!2stn",
        back1:"../ressources-map/ariana/ariana2.png",
        back2:"../ressources-map/ariana/ariana.png"
    },
    {
        nom:"Beja",
        description:"Connu par ses richesses agricoles, le gouvernorat de BEJA est un territoire aux ressources naturelles très appréciables",
        titre:"Ou aller à Beja",
        description2:"Dans notre exploration de la magnifique région de Beja , nous sommes impatients de vous présenter une sélection soigneusement choisie d'endroits exceptionnels à visiter",
        photo1 :"../ressources-map/beja/ain-tounga.jpg",
        photo1_title:"Ain tounga",
        photo1_subtitle:"loisirs",
        photo1_description:"Aïn Tounga est un site archéologique tunisien situé à une quinzaine de kilomètres de la ville de Testour, non loin du site de Dougga, qui abrite les vestiges de la cité antique de Thignica. Les vestiges les plus impressionnants consistent en des restes d'une forteresse byzantine",
        photo2: "../ressources-map/beja/barrage-sidi-barrak.jpg",
        photo2_title:"barrage sidi barrak ",
        photo2_subtitle:"Nature",
        photo2_description:" Découvrez le charmant barrage de Sidi Barrak à Béja. Une destination pittoresque qui offre une expérience paisible, parfaite pour une escapade rafraîchissante. Ajoutez cette belle attraction à votre liste de visites lors de votre séjour à Béja",
        photo3: "../ressources-map/beja/douga.jpg",
        photo3_title:"Douga",
        photo3_subtitle:"Nature",
        photo3_description:"Explorez le site archéologique de Dougga, également connu sous le nom de Thugga, situé dans la délégation de Téboursouk au Nord-Ouest de la Tunisie. Classé au patrimoine mondial de l'UNESCO en 1997, Dougga est reconnu comme la « petite ville romaine la mieux conservée de l'Afrique du Nord ». Profitez de cette destination exceptionnelle pour plonger dans l'histoire et découvrir des vestiges bien préservés de l'ancienne civilisation romaine",
        lien_youtube:"https://www.youtube.com/embed/ZEGNx11n-Y0?si=XTqkCNdpLSB4BYdG",
        map_title:"Explorez Beja à travers notre carte.",
        map_src:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d25581.618558414564!2d9.18760225!3d36.7297099!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12fb588073d15b35%3A0x67e6f1f9d0f178b2!2zQsOpamE!5e0!3m2!1sfr!2stn!4v1706207075877!5m2!1sfr!2stn",
        back1:"../ressources-map/beja/beja1.png",
        back2:"../ressources-map/beja/beja2.png"
    },
    {
        nom:"Ben Arous",
        description:"Le gouvernorat de Ben Arous se situe au sud-est de la région du Grand Tunis et se caractérise par des paysages divers alliant entre la mer, la montagne et des superficies verdoyantes.",
        titre:"Ou aller à Ben Arous",
        description2:"Dans notre exploration de la magnifique région de Ben Arous, nous sommes impatients de vous présenter une sélection soigneusement choisie d'endroits exceptionnels à visiter",
        photo1 :"../ressources-map/benarous/Parc_national_de_Boukornine.jpg",
        photo1_title:"Park de Boukernine",
        photo1_subtitle:"nature",
        photo1_description:"Ne manquez pas l'opportunité de visiter le Parc National de Boukornine. Niché dans une splendide région naturelle, ce parc offre une escapade idéale pour les amoureux de la nature",
        photo2: "../ressources-map/benarous/uthina.jpg",
        photo2_title:"Uthina",
        photo2_subtitle:"Histoire",
        photo2_description:"Découvrez Uthina, un site archéologique captivant situé en Tunisie. Imprégnez-vous de l'histoire ancienne en explorant les ruines bien préservées de cette ancienne cité romaine. Uthina offre une plongée fascinante dans le passé, faisant de votre visite une expérience enrichissante.",
        photo3: "../ressources-map/benarous/tarenti-ferme.jpg",
        photo3_title:"Tarenti Ferme",
        photo3_subtitle:"Nature",
        photo3_description:" Explorez la Tarenti Ferme, une destination unique pour une expérience authentique. Immergez-vous dans la vie agricole, découvrez des produits locaux de qualité et profitez d'une escapade rurale mémorable à la Tarenti Ferme",
        lien_youtube:"https://www.youtube.com/embed/DeGLqQOYzd4?si=4IOGkU9ee9MvVjeb",
        map_title:"Explorez Ben Arous à travers notre carte.",
        map_src:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d25576.018236824944!2d10.214047275892954!3d36.746516362836275!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12fd496f233f4109%3A0x3bfd822b0ccc697b!2sBen%20Arous!5e0!3m2!1sfr!2stn!4v1706282051499!5m2!1sfr!2stn",
        back1:"../ressources-map/benarous/benarous1.png",
        back2:"../ressources-map/benarous/benarous2.png"
    },
    {
        nom:"Bizerte",
        description:"Bizerte ou Banzart est une ville du nord de la Tunisie située entre la mer Méditerranée et le lac de Bizerte. Elle est le chef-lieu d'un gouvernorat peuplé de plus d'un demi-million d'habitants",
        titre:"Ou aller à Bizerte",
        description2:"Dans notre exploration de la magnifique région de Bizerte, nous sommes impatients de vous présenter une sélection soigneusement choisie d'endroits exceptionnels à visiter",
        photo1 :"../ressources-map/bizerte/Ichkeu.jpg",
        photo1_title:"Park Ichkeul",
        photo1_subtitle:"nature",
        photo1_description:"Explorez la beauté naturelle préservée du Parc National d'Ichkeul à Bizerte. Classé au patrimoine mondial de l'UNESCO, ce parc offre un sanctuaire pour une variété d'oiseaux migrateurs et une vue spectaculaire sur le lac. Plongez dans la biodiversité exceptionnelle et profitez d'une expérience paisible au cœur de la nature à Ichkeul.",
        photo2: "../ressources-map/bizerte/qsiba.jpg",
        photo2_title:"Qsiba",
        photo2_subtitle:"port",
        photo2_description:"Le Vieux Port de Bizerte, chargé d'histoire, est un lieu emblématique de la ville. Niché entre des remparts anciens, ce port pittoresque offre une atmosphère authentique avec ses bateaux de pêche traditionnels amarrés le long des quais. Explorez les ruelles charmantes, profitez des vues sur la mer Méditerranée, et imprégnez-vous de l'ambiance maritime unique de ce joyau historique",
        photo3: "../ressources-map/bizerte/utica.jpg",
        photo3_title:"Utica",
        photo3_subtitle:"Histoire",
        photo3_description:"Utica, un site archéologique près de Bizerte, en Tunisie, abrite des vestiges anciens remontant au IXe siècle av. J.-C. Fondée par les Phéniciens, cette ville a joué un rôle clé au cours des guerres puniques. Explorez les ruines romaines et phéniciennes, découvrez l'histoire ancienne et imprégnez-vous de l'atmosphère antique de ce site historique",
        lien_youtube:"https://www.youtube.com/embed/uyeXpLjqgxw?si=bHIAjXpwfGk9xI8s",
        map_title:"Explorez Bizerte à travers notre carte.",
        map_src:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d50793.449522253424!2d9.820304540783313!3d37.28113430569627!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12e31e4db2105f13%3A0xf44361a00609c69e!2sBizerte!5e0!3m2!1sfr!2stn!4v1706288088864!5m2!1sfr!2stn",
        back1:"../ressources-map/bizerte/bizerte1.png",
        back2:"../ressources-map/bizerte/bizerte2.png"
    },
    {
        nom:"Gabes",
        description:"Gabès est une ville du sud-est de la Tunisie, située dans la région historique de l'Arad. Plus grande ville du Sud tunisien après Sfax",
        titre:"Ou aller à Gabes",
        description2:"Dans notre exploration de la magnifique région de Gabes, nous sommes impatients de vous présenter une sélection soigneusement choisie d'endroits exceptionnels à visiter",
        photo1 :"../ressources-map/gabes/Eglise_de_Gabes.jpg",
        photo1_title:"Eglise de Gabes",
        photo1_subtitle:"religion",
        photo1_description:"L'église de Gabès, située au cœur de la ville, est un joyau architectural chargé d'histoire. Témoin de la diversité culturelle de la région, cette église offre un lieu de culte empreint de spiritualité. Explorez son architecture unique et découvrez la riche signification culturelle de cet édifice au sein de la communauté gabésienne",
        photo2: "../ressources-map/gabes/matmata.jpg",
        photo2_title:"Matmata",
        photo2_subtitle:"Histoire",
        photo2_description:"Découvrez Matmata, une région unique du gouvernorat de Gabès, en Tunisie. Célèbre pour ses maisons troglodytes, creusées dans les collines, Matmata offre une expérience immersive dans un paysage lunaire. Explorez ces habitations particulières, imprégnez-vous de la culture locale et plongez dans l'authenticité de ce joyau du sud tunisien. Une aventure hors du commun entre tradition, architecture atypique et hospitalité locale",
        photo3: "../ressources-map/gabes/musee.jpg",
        photo3_title:"Musée d'art et de tradition",
        photo3_subtitle:"Tradition",
        photo3_description:" Découvrez le riche héritage culturel de Gabès au Musée d'Arts et de Traditions Populaires. Des expositions captivantes mettent en lumière l'artisanat, les costumes traditionnels et les coutumes locales, offrant une immersion authentique dans la vie quotidienne de cette communauté dynamique",
        lien_youtube:"https://www.youtube.com/embed/Fza0t7LwS2M?si=zr0yaV3KqiAZuLac",
        map_title:"Explorez Gabes à travers notre carte.",
        map_src:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d26496.10588618566!2d10.082058617475939!3d33.889312961151894!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12556fc5487bd237%3A0x4980e09bdb547a86!2zR2Fiw6hz!5e0!3m2!1sfr!2stn!4v1706288567347!5m2!1sfr!2stn",
        back1:"../ressources-map/gabes/gabes1.png",
        back2:"../ressources-map/gabes/gabes2.png"
    },
    {
        nom:"Gafsa",
        description:"Gafsa, l'antique Capsa, est une ville du sud-ouest de la Tunisie et le chef-lieu du gouvernorat éponyme",
        titre:"Ou aller à Gafsa",
        description2:"Dans notre exploration de la magnifique région de Gafsa, nous sommes impatients de vous présenter une sélection soigneusement choisie d'endroits exceptionnels à visiter",
        photo1 :"../ressources-map/gafsa/oisis.jpg",
        photo1_title:"Oasis",
        photo1_subtitle:"Nature",
        photo1_description:"Explorez l'Oasis de Gafsa, un joyau naturel niché dans la région de Gafsa en Tunisie. Cette oasis offre une échappée authentique au milieu de palmiers verdoyants et de paysages paisibles. Promenez-vous à travers les sentiers ombragés, découvrez la vie oasisienne traditionnelle et laissez-vous imprégner par la sérénité de cet endroit préservé au cœur du désert tunisien. Une expérience rafraîchissante où la nature et la culture se rencontrent harmonieusement",
        photo2: "../ressources-map/gafsa/piscine.jpg",
        photo2_title:"Piscine Romains",
        photo2_subtitle:"Histoire",
        photo2_description:"Découvrez les Piscines Romaines de Gafsa, un site archéologique impressionnant situé dans la région de Gafsa en Tunisie. Ces piscines, datant de l'époque romaine, témoignent de la grandeur architecturale de cette civilisation ancienne. Entourées de vestiges bien préservés, les Piscines Romaines offrent aux visiteurs une plongée fascinante dans l'histoire, où l'ingénierie romaine se marie harmonieusement avec le paysage tunisien. Explorez ces piscines antiques et revivez l'opulence de l'époque romaine dans un cadre unique au cœur de Gafsa",
        photo3: "../ressources-map/gafsa/sened.jpg",
        photo3_title:"Sened",
        photo3_subtitle:"Histoire",
        photo3_description:"Explorez la région de Sened à Gafsa, un trésor caché de la Tunisie. Imprégnée d'histoire et de traditions, Sened offre des paysages désertiques à couper le souffle et des expériences culturelles riches. Des sites archéologiques aux coutumes locales, plongez dans l'authenticité de Sened et découvrez la beauté préservée de cette région du sud tunisien. Une escapade où l'histoire et la nature se rencontrent harmonieusement",
        lien_youtube:"https://www.youtube.com/embed/VHkdwbfJGPQ?si=n5qT57cd9T53JoxM",
        map_title:"Explorez Gafsa à travers notre carte ",
        map_src:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d52654.80312124064!2d8.732460756426276!3d34.42865518978788!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12f896fa5476901f%3A0x873608732b8975d5!2sGafsa!5e0!3m2!1sfr!2stn!4v1706288958053!5m2!1sfr!2stn",
        back1:"../ressources-map/gafsa/gafsa1.png",
        back2:"../ressources-map/gafsa/gafsa2.png" 
    },
    {
        nom:"Kasserine",
        description:"Kasserine, ville pittoresque de l'ouest de la Tunisie, allie charme historique et vitalité moderne au cœur du gouvernorat éponyme",
        titre:"Ou aller à Kasserine",
        description2:"Dans notre exploration de la magnifique région de Kasserine, nous sommes impatients de vous présenter une sélection soigneusement choisie d'endroits exceptionnels à visiter",
        photo1 :"../ressources-map/gasserine/sbitla.jpg",
        photo1_title:"Sbitla",
        photo1_subtitle:"Histoire",
        photo1_description:" Découvrez Sbeitla à Kasserine, une ville tunisienne imprégnée d'histoire et de vestiges romains. Les ruines de Sbeitla révèlent l'ancienne splendeur de cette cité romaine, avec ses temples imposants, ses arcs de triomphe et ses théâtres bien préservés. Explorez ce site archéologique captivant, plongez dans le passé de la civilisation romaine et admirez l'architecture grandiose qui témoigne de l'ingéniosité de cette époque. Une visite à Sbeitla promet une expérience immersive au cœur de l'héritage antique de la Tunisie",
        photo2: "../ressources-map/gasserine/haidra-en-hiver.jpg",
        photo2_title:"Haidra",
        photo2_subtitle:"Histoire",
        photo2_description:"Explorez Haidra à Kasserine, un site archéologique captivant en Tunisie. Ancienne cité romaine, Haidra présente des vestiges bien conservés, notamment des temples, des thermes et des amphithéâtres, offrant aux visiteurs un voyage dans le temps. Les ruines majestueuses, associées à l'atmosphère historique, font de Haidra un lieu incontournable pour les amateurs d'histoire et les passionnés d'archéologie. Plongez dans le passé de la civilisation romaine au cœur de cette cité antique",
        photo3: "../ressources-map/gasserine/Ancient-Ammaedara.jpg",
        photo3_title:"Ammaedara",
        photo3_subtitle:"Histoire",
        photo3_description:"Explorez l'ancienne Ammaedara à Kasserine, un site archéologique fascinant qui révèle l'héritage de l'antique cité romaine. Les vestiges bien conservés d'Ammaedara dévoilent une histoire riche à travers des temples, des arcs et des structures qui témoignent de l'ingénierie romaine. Imprégnez-vous de l'atmosphère historique en vous promenant parmi ces ruines, et plongez dans le passé glorieux de cette ancienne cité au cœur de la Tunisie. Une expérience immersive qui transporte les visiteurs à travers les époques",
        lien_youtube:"https://www.youtube.com/embed/u4YeC9fOJoY?si=cGx0yNHQOW_VX5n_",
        map_title:"Explorez Kasserine à travers notre carte ",
        map_src:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d52183.20584322028!2d8.783568165107662!3d35.170326038845616!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12f93e03277f3b3d%3A0x9165782c2e6df471!2sKasserine!5e0!3m2!1sfr!2stn!4v1706289380157!5m2!1sfr!2stn",
        back1:"../ressources-map/gasserine/gasserine1.png",
        back1:"../ressources-map/gasserine/gasserine2.png",
    },
    {
        nom:"Kebili",
        description:"Kebili, ville nichée au sud de la Tunisie, dévoile son charme envoûtant entre maisons ocre et dunes dorées, offrant une expérience unique au cœur du Sahara",
        titre:"Ou aller à Kebili",
        description2:"Dans notre exploration de la magnifique région de Kebili, nous sommes impatients de vous présenter une sélection soigneusement choisie d'endroits exceptionnels à visiter",
        photo1 :"../ressources-map/gbeli/ancienne-kebeli.jpg",
        photo1_title:"Ancienne Kebili",
        photo1_subtitle:"Histoire",
        photo1_description:"Explorez l'ancienne Kebili, une ville chargée d'histoire au cœur du désert tunisien. Les vestiges antiques de Kebili racontent une histoire fascinante à travers des ruines bien préservées, témoignant de l'ancienne civilisation qui a prospéré dans cette région. Avec ses structures anciennes, ses ruelles étroites et son ambiance unique, l'ancienne Kebili offre une immersion authentique dans le passé, permettant aux visiteurs de remonter le temps et de découvrir la grandeur de cette cité ancienne. Une expérience inoubliable au carrefour de l'histoire et de la culture",
        photo2: "../ressources-map/gbeli/sahara-museum.jpg",
        photo2_title:"Sahara Musée",
        photo2_subtitle:"Histoire",
        photo2_description:"Explorez le Musée du Sahara à Kebili, une fenêtre captivante sur la richesse et la diversité du désert tunisien. Ce musée met en lumière l'histoire ancienne, la géologie unique et les traditions des communautés sahariennes. Des expositions soigneusement présentées, des artefacts fascinants et des témoignages culturels offrent aux visiteurs une immersion complète dans la vie du Sahara. Plongez dans la beauté mystique de cette région à travers les trésors préservés au Musée du Sahara, une expérience éducative et enrichissante au cœur de Kebili.",
        photo3: "../ressources-map/gbeli/sahha-sahara.jpg",
        photo3_title:"Saha Sahara",
        photo3_subtitle:"Nature",
        photo3_description:"Explorez la beauté sans fin du Sahara à Kebili, où des dunes majestueuses et des paysages infinis captivent les sens. Le Sahara de Kebili offre une expérience immersive, avec ses vastes étendues de sable doré et ses oasis tranquilles. Imprégnez-vous de l'atmosphère sereine, découvrez la vie oasisienne traditionnelle et admirez le coucher de soleil spectaculaire qui peint le désert de nuances chaudes. Une aventure au cœur du Sahara de Kebili, où la nature révèle sa grandeur infinie",
        lien_youtube:"https://www.youtube.com/embed/pRLLQaRGPXc?si=CX9aNnUq_z-ZYRhR",
        map_title:"Explorez Kebili à travers notre carte ",
        map_src:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d26553.621846658127!2d8.952912916951995!3d33.70370269305825!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12566e541bcc6359%3A0x79fc96a6bcfd0b81!2sKebili!5e0!3m2!1sfr!2stn!4v1706289781138!5m2!1sfr!2stn",
        back1:"../ressources-map/gbeli/gbeli1.png", 
        back2:"../ressources-map/gbeli/gbeli2.png"
    },
    {
        nom:"Jendouba",
        description:"Jendouba, une perle du nord-ouest tunisien. Entourée par les collines verdoyantes et ponctuée d'oliveraies, cette ville pittoresque offre une atmosphère paisible où l'héritage historique se mêle à la beauté naturelle",
        titre:"Ou aller à Jendouba",
        description2:"Dans notre exploration de la magnifique région de Jendouba, nous sommes impatients de vous présenter une sélection soigneusement choisie d'endroits exceptionnels à visiter",
        photo1 :"../ressources-map/jendouba/ain-drahem.jpg",
        photo1_title:"Ain Drahem",
        photo1_subtitle:"Nature",
        photo1_description:"Explorez Ain Draham, un joyau niché dans les montagnes du nord-ouest de la Tunisie. Célèbre pour ses paysages montagneux verdoyants, ses forêts de pins et ses sources d'eau cristalline, Ain Draham offre une retraite rafraîchissante loin de l'agitation urbaine",
        photo2: "../ressources-map/jendouba/tabarka.jpg",
        photo2_title:"Tabarka",
        photo2_subtitle:"Nature",
        photo2_description:"Découvrez Tabarka, une perle méditerranéenne nichée sur la côte nord-ouest de la Tunisie. Célèbre pour ses plages de sable doré, son port pittoresque et ses eaux cristallines, Tabarka offre un cadre idyllique pour les amateurs de soleil et de mer. La ville est également réputée pour ses formations rocheuses impressionnantes, qui donne à la côte une allure spectaculaire. Avec son mélange unique de nature préservée et de charme méditerranéen, Tabarka promet une escapade balnéaire mémorable.",
        photo3: "../ressources-map/jendouba/bulla-regia.jpg",
        photo3_title:"Bulla Regia",
        photo3_subtitle:"Histoire",
        photo3_description:"Explorez Bulla Regia, un site archéologique remarquable situé en Tunisie. Connu pour ses vestiges romains bien préservés, Bulla Regia offre une expérience unique où les visiteurs peuvent découvrir des maisons souterraines, caractéristiques de la ville antique. Les ruines comprennent des mosaïques impressionnantes, des temples et des structures qui témoignent de la grandeur de la civilisation romaine.",
        lien_youtube:"https://www.youtube.com/embed/JoOpZRlXJvc?si=w9jh0s_AwMqCHy6n",
        map_title:"Explorez Jendouba à travers notre carte ",
        map_src:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d25656.842531096452!2d8.758291925151058!3d36.50331977603911!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12fb124ea3099bff%3A0x6bef4f37f93342da!2sJendouba!5e0!3m2!1sfr!2stn!4v1706290223538!5m2!1sfr!2stn",
        back1:"../ressources-map/jendouba/jendouba1.png",
        back2:"../ressources-map/jendouba/jendouba2.png" 
    },
    {
        nom:"Kairouan",
        description:"Kairouan, la cité des mille coupoles et berceau de la spiritualité en Tunisie. Avec ses ruelles étroites aux murs blanchis à la chaux, ses médinas animées et ses joyaux architecturaux islamiques",
        titre:"Ou aller à Kairouan",
        description2:"Dans notre exploration de la magnifique région de Kairouan, nous sommes impatients de vous présenter une sélection soigneusement choisie d'endroits exceptionnels à visiter",
        photo1 :"../ressources-map/kairouen/bassin-aghlabite.jpg",
        photo1_title:"Bassin Aghlabide",
        photo1_subtitle:"Histoire",
        photo1_description:"Découvrez le Bassin Aghlabide à Kairouan, un chef-d'œuvre architectural emblématique de l'ère islamique. Construit au IXe siècle, ce bassin reflète l'ingénierie avancée des Aghlabides, avec son système sophistiqué d'approvisionnement en eau. Niché dans un cadre paisible, entouré d'arcades élégantes et de jardins luxuriants, le bassin offre une expérience sereine",
        photo2: "../ressources-map/kairouen/Bir-Barrouta.jpg",
        photo2_title:"Bir Barrouta",
        photo2_subtitle:"Histoire",
        photo2_description:"Explorez Bir Barouta à Kairouan, un puits emblématique qui incarne l'histoire et la spiritualité de la ville. Ce puits ancestral, réputé pour ses eaux pures, a une signification particulière dans la culture locale. Entouré d'une atmosphère sacrée, Bir Barouta est un lieu de recueillement où les visiteurs peuvent ressentir la spiritualité de Kairouan",
        photo3: "../ressources-map/kairouen/le-grand-mosque.jpg",
        photo3_title:"Le Grand Mosque",
        photo3_subtitle:"Histoire",
        photo3_description:"Explorez la Grande Mosquée de Kairouan, un chef-d'œuvre architectural au cœur de la spiritualité islamique en Tunisie. Datant du VIIe siècle, cette mosquée emblématique est l'une des plus anciennes et des plus importantes du monde musulman. Les colonnes de marbre, les arcs élégants et le minaret impressionnant créent une atmosphère majestueuse",
        lien_youtube:"https://www.youtube.com/embed/ZrCHDC3uZhg?si=JwuVqRoPckL8wfYQ",
        map_title:"Explorez Kairouan à travers notre carte ",
        map_src:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d51858.30105744803!2d10.06324742109831!3d35.67346065929956!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12fdc54531303f79%3A0xbba4cacca78e555e!2sKairouan!5e0!3m2!1sfr!2stn!4v1706290674680!5m2!1sfr!2stn",
        back1:"../ressources-map/kairouen/kair1.png",
        back2:"../ressources-map/kairouen/kair2.png"
    },
    {
        nom:"Kef",
        description:"Entre tradition et modernité, Le Kef offre une expérience authentique où la culture et la nature se rencontrent avec élégance",
        titre:"Ou aller à Kef",
        description2:"Dans notre exploration de la magnifique région de Kef, nous sommes impatients de vous présenter une sélection soigneusement choisie d'endroits exceptionnels à visiter",
        photo1 :"../ressources-map/kef/kasba-kef.jpg",
        photo1_title:"Kasba",
        photo1_subtitle:"Histoire",
        photo1_description:"Explorez la Kasbah du Kef, une forteresse historique perchée sur les collines du nord-ouest de la Tunisie. Datant de l'époque médiévale, cette Kasbah offre une vue panoramique imprenable sur la ville du Kef. Les murs de pierre robustes, les ruelles étroites et les cours intérieures évoquent une époque révolue",
        photo2: "../ressources-map/kef/table-jugurtha.jpg",
        photo2_title:"Table Jugurtha",
        photo2_subtitle:"Nature",
        photo2_description:"Explorez la Table de Jugurtha au Kef, un site archéologique exceptionnel imprégné d'histoire ancienne. Cette table rocheuse massive, perchée sur les hauteurs, offre non seulement des vues panoramiques spectaculaires sur la région environnante, mais elle est également associée à l'époque du roi numide Jugurtha",
        photo3: "../ressources-map/kef/temple-of-water.jpg",
        photo3_title:"Le temple des eaux",
        photo3_subtitle:"Nature",
        photo3_description:"Explorez le Temple de l'Eau au Kef, une structure remarquable qui témoigne de l'ingéniosité architecturale antique. Cet ancien temple, dédié à l'eau, présente des colonnes majestueuses et des détails sculpturaux. Niché dans un cadre pittoresque, le temple offre une atmosphère paisible et invite les visiteurs à imaginer son rôle sacré dans l'Antiquité",
        lien_youtube:"https://www.youtube.com/embed/xKpNfEQQrWE?si=X8gCudZ78UBF1a8R",
        map_title:"Explorez Kef à travers notre carte ",
        map_src:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d51535.75753367285!2d8.661121377052835!3d36.166923385851426!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12fba448bbb60817%3A0xd20dcc094b5debbf!2sLe%20Kef!5e0!3m2!1sfr!2stn!4v1706291281102!5m2!1sfr!2stn",
        back1:"../ressources-map/kef/kef1.png",
        back2:"../ressources-map/kef/kef2.png"
    },
    {
        nom:"Mahdia",
        description:"Mahdia, une perle méditerranéenne où l'histoire se mêle à la douceur du littoral. Les ruelles de la médina, teintées de blanc et de bleu, dévoilent un patrimoine riche",
        titre:"Ou aller à Mahdia",
        description2:"Dans notre exploration de la magnifique région de Mahdia, nous sommes impatients de vous présenter une sélection soigneusement choisie d'endroits exceptionnels à visiter",
        photo1 :"../ressources-map/mahdia/borj-kbir.jpg",
        photo1_title:"Borj Lekbir",
        photo1_subtitle:"Histoire",
        photo1_description:"Découvrez le Borj Kebir à Mahdia, une forteresse maritime historique qui domine la côte méditerranéenne. Érigé au XVIe siècle, ce fort imposant est un témoignage de l'histoire militaire de la Tunisie. Avec ses murs massifs, ses tours de guet et ses canons pointés vers la mer, le Borj Kebir offre une vue panoramique sur le littoral. En explorant ses remparts, les visiteurs peuvent se plonger dans l'histoire maritime de Mahdia, apprécier l'architecture militaire de l'époque ottomane et admirer le panorama pittoresque qui s'étend à perte de vue",
        photo2: "../ressources-map/mahdia/skifa-kahla.jpg",
        photo2_title:"Skifa Kahla",
        photo2_subtitle:"Histoire",
        photo2_description:"Explorez Skifa Kahla à Mahdia, un pont historique qui enjambe la rivière Oued El Maleh. Construit au XIIIe siècle, ce pont emblématique est un exemple remarquable de l'architecture médiévale. Les arches élégantes et les murs en pierre témoignent de la construction ingénieuse de l'époque",
        photo3: "../ressources-map/mahdia/plage.jpg",
        photo3_title:"Plage",
        photo3_subtitle:"Nature",
        photo3_description:"Découvrez la Plage de Mahdia, une étendue de sable doré qui borde les eaux cristallines de la mer Méditerranée. Réputée pour sa beauté naturelle, cette plage offre aux visiteurs un havre de paix où ils peuvent se détendre, se baigner et profiter du soleil. Les douces vagues viennent caresser le rivage, créant une symphonie apaisante pour ceux qui recherchent la sérénité au bord de la mer",
        lien_youtube:"https://www.youtube.com/embed/bNLYljf8gug?si=KnBhQ4f1-9cLCfGJ",
        map_title:"Explorez Mahdia à travers notre carte ",
        map_src:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d25983.842354821492!2d11.031457372154273!3d35.50476548564298!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x130223f5186c6cf9%3A0x675f7b734dffa5bb!2sMahdia!5e0!3m2!1sfr!2stn!4v1706292011449!5m2!1sfr!2stn",
        back1:"../ressources-map/mahdia/mahdia1.png",
        back2:"../ressources-map/mahdia/mahdia2.png" 
    },
    {
        nom:"Manouba",
        description:"Les vestiges historiques, tels que le palais de la ville, racontent l'histoire riche de Manouba, tandis que ses habitants chaleureux ajoutent une touche conviviale à cette destination tunisienne ",
        titre:"Ou aller à Manouba",
        description2:"Dans notre exploration de la magnifique région de Manouba, nous sommes impatients de vous présenter une sélection soigneusement choisie d'endroits exceptionnels à visiter",
        photo1 :"../ressources-map/manouba/kobet-nhas.jpg",
        photo1_title:"Kobet Nhas",
        photo1_subtitle:"Histoire",
        photo1_description:"Explorez Kobet Nhas à Manouba, une région qui incarne la beauté naturelle et l'authenticité de la Tunisie. Niché entre collines et vergers, Kobet Nhas offre un paysage pittoresque où les oliveraies s'étendent à perte de vue",
        photo2: "../ressources-map/manouba/Musée-militaire.jpg",
        photo2_title:"Musée Militaire",
        photo2_subtitle:"Histoire",
        photo2_description:"collection diversifiée d'artefacts, d'uniformes et de matériel militaire, offrant aux visiteurs un aperçu approfondi des événements clés du passé. LesExplorez le Musée Militaire de Manouba, une vitrine impressionnante de l'histoire militaire de la Tunisie. Ce musée captivant abrite une  expositions soigneusement organisées racontent l'héritage militaire du pays, mettant en lumière le courage et la détermination de ceux qui ont servi",
        photo3: "../ressources-map/manouba/Sebkhet-Sejoumi.jpg",
        photo3_title:"Sebkhet Sejoumi",
        photo3_subtitle:"Nature",
        photo3_description:"Explorez la Sabkhet Essejoumi à Manouba, une étendue de salines et de marais salants qui captivent par leur beauté naturelle unique. Cette zone humide offre un écosystème fascinant où l'eau reflète le ciel, créant des paysages changeants au gré des saisons. Les flamants roses et d'autres oiseaux migrateurs ajoutent une touche de vie à cet environnement salin",
        lien_youtube:"https://www.youtube.com/embed/sXyCiFftiFs?si=ZZt7zbxPncGDHb5x",
        map_title:"Explorez Manouba à travers notre carte ",
        map_src:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d25554.871771887785!2d10.057060476087122!3d36.80991708324369!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12fd326a6997b651%3A0xae1949b938bf5487!2sManouba!5e0!3m2!1sfr!2stn!4v1706292397729!5m2!1sfr!2stn",
        back1:"../ressources-map/manouba/manouba1.png",
        back2:"../ressources-map/manouba/manouba2.png"
    },
    {
        nom:"Medenine",
        description:"Medenine, une ville nichée au cœur du sud tunisien, où l'histoire s'entrelace avec le désert environnant",
        titre:"Ou aller à Medenine",
        description2:"Dans notre exploration de la magnifique région de Medenine, nous sommes impatients de vous présenter une sélection soigneusement choisie d'endroits exceptionnels à visiter",
        photo1 :"../ressources-map/mednin/jerba.jpg",
        photo1_title:"Djerba",
        photo1_subtitle:"Nature",
        photo1_description:"Découvrez Djerba, une perle enchanteresse de la Méditerranée qui séduit les visiteurs par son charme insulaire et sa riche histoire. L'île de Djerba, aux côtes baignées par les eaux cristallines, offre des plages de sable doré propices à la détente et au ressourcement",
        photo2: "../ressources-map/mednin/zarzis.jpg",
        photo2_title:"Zarzis",
        photo2_subtitle:"Nature",
        photo2_description:"Découvrez Zarzis, une perle méditerranéenne située sur la côte sud-est de la Tunisie. Cette ville côtière séduit par ses plages de sable doré baignées par les eaux cristallines de la mer Méditerranée. Zarzis offre une atmosphère détendue où les visiteurs peuvent profiter du soleil, se promener le long du littoral et s'immerger dans la douce brise marine",
        photo3: "../ressources-map/mednin/oasis-tamerza.jpg",
        photo3_title:"Tamerza Oasis",
        photo3_subtitle:"Nature",
        photo3_description:"Explorez Tamerza, une oasis majestueuse située au cœur du désert tunisien. Nichée entre les dunes de sable, Tamerza offre une retraite paisible où les palmiers s'élèvent fièrement et où les sources naturelles créent des rivières serpentines à travers le paysage aride",
        lien_youtube:"https://www.youtube.com/embed/HAdhrrb-W20?si=18D2SsQDV-CmDKLH",
        map_title:"Explorez Medenine à travers notre carte ",
        map_src:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d53326.93550713658!2d10.450056944083823!3d33.34668789932518!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1254d62866735147%3A0xf085df215e783c40!2zTcOpZGVuaW5l!5e0!3m2!1sfr!2stn!4v1706292775039!5m2!1sfr!2stn",
        back1:"../ressources-map/mednin/medenin1.png",
        back2:"../ressources-map/mednin/medenin2.png"
    },
    {
        nom:"Monastir",
        description:" Monastir, une perle méditerranéenne où l'histoire rencontre la splendeur balnéaire",
        titre:"Ou aller à Monastir",
        description2:"Dans notre exploration de la magnifique région de Monastir, nous sommes impatients de vous présenter une sélection soigneusement choisie d'endroits exceptionnels à visiter",
        photo1 :"../ressources-map/monastir/bourguiba-mausoleum.jpg",
        photo1_title:"Musée de Bourguiba",
        photo1_subtitle:"Histoire",
        photo1_description:"Découvrez le Musée Bourguiba à Monastir, un lieu dédié à l'héritage exceptionnel de Habib Bourguiba, le premier président de la République tunisienne. Situé dans le palais présidentiel de Skanès, le musée offre une plongée captivante dans la vie et le leadership de Bourguiba",
        photo2: "../ressources-map/monastir/kuriat-islands.jpg",
        photo2_title:"Kuriat",
        photo2_subtitle:"Nature",
        photo2_description:"Explorez les Îles Kuriat au large de Monastir, un trésor naturel niché dans les eaux cristallines de la mer Méditerranée. Ces îles préservées offrent un refuge tranquille où la beauté naturelle rencontre la diversité marine. Les plages de sable fin, les eaux turquoise et les récifs coralliens font des Îles Kuriat un paradis pour les amateurs de plongée et de snorkeling",
        photo3: "../ressources-map/monastir/monastir-marina.jpg",
        photo3_title:"Marina",
        photo3_subtitle:"Nature",
        photo3_description:"Explorez la Marina de Monastir, un havre de paix méditerranéen où la beauté naturelle se marie à l'élégance nautique. Les eaux calmes de la mer Méditerranée bercent les yachts scintillants qui ornent la marina, créant un panorama captivant. Les palmiers qui bordent les quais ajoutent une touche de verdure à ce paysage marin",
        lien_youtube:"https://www.youtube.com/embed/ucXK2HKShIM?si=b2I6BhkZJ8cTYTXK",
        map_title:"Explorez Monastir à travers notre carte ",
        map_src:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d51805.70217715147!2d10.769239822068835!3d35.754334481916466!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x130212b61d744f59%3A0xf284743e1d3e40ef!2sMonastir!5e0!3m2!1sfr!2stn!4v1706293130742!5m2!1sfr!2stn",
        back1:"../ressources-map/monastir/monastir1.png",
        back2:"../ressources-map/monastir/monastir2.png"
    },
    {
        nom:"Nabeul",
        description:"Célèbre pour ses plages de sable fin et ses marchés animés, Nabeul offre une expérience balnéaire authentique",
        titre:"Ou aller à Nabeul",
        description2:"Dans notre exploration de la magnifique région de Nabeul, nous sommes impatients de vous présenter une sélection soigneusement choisie d'endroits exceptionnels à visiter",
        photo1 :"../ressources-map/nabeul/hammamet.jpg",
        photo1_title:"Hammamet",
        photo1_subtitle:"loisirs",
        photo1_description:"Explorez Hammamet à Nabeul, une perle méditerranéenne qui marie l'histoire, la culture et la beauté côtière. Connue comme la Station balnéaire des Jasmins, Hammamet offre des plages de sable fin caressées par les eaux turquoise de la mer Méditerranée",
        photo2: "../ressources-map/nabeul/kelibia.jpg",
        photo2_title:"Kelibia",
        photo2_subtitle:"Nature",
        photo2_description:"Explorez Kelibia à Nabeul, une destination méditerranéenne qui charme les visiteurs par son mélange captivant de beauté naturelle et de patrimoine culturel. Cette ville côtière, située sur la péninsule du Cap Bon, est célèbre pour sa forteresse imposante qui domine la mer Méditerranée.",
        photo3: "../ressources-map/nabeul/korbous.jpg",
        photo3_title:"Korbous",
        photo3_subtitle:"Nature",
        photo3_description:"Découvrez Korbos à Nabeul, une charmante localité qui allie le charme côtier à l'authenticité tunisienne. Bordé par les eaux scintillantes de la mer Méditerranée, Korbos offre des plages de sable doré où les visiteurs peuvent se détendre et profiter du climat ensoleillé",
        lien_youtube:"https://www.youtube.com/embed/ImK_LesbI-8?si=JSgP3cysLnhXIIAA",
        map_title:"Explorez Nabeul à travers notre carte ",
        map_src:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d51347.37577112283!2d10.674141930533887!3d36.452457160504764!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x13029895efbdd3d3%3A0x2e5d60d1569ce4fe!2zTmFiZXVs4oCO!5e0!3m2!1sfr!2stn!4v1706294979916!5m2!1sfr!2stn",
        back1:"../ressources-map/nabeul/nabeul1.png",
        back2:"../ressources-map/nabeul/nabeul2.png"
    },
    {
        nom:"Sfax",
        description:"Sfax, la perle du sud tunisien, où l'histoire maritime et l'activité économique se rencontrent dans une harmonie fascinante.",
        titre:"Ou aller à Sfax",
        description2:"Dans notre exploration de la magnifique région de Sfax, nous sommes impatients de vous présenter une sélection soigneusement choisie d'endroits exceptionnels à visiter",
        photo1 :"../ressources-map/sfax/Bab-Diwan.jpg",
        photo1_title:"Bab Diwan",
        photo1_subtitle:"Histoire",
        photo1_description:"Explorez Beb Diwan à Sfax, un quartier qui porte l'histoire ancienne de la médina de la ville. Beb Diwan est un mélange fascinant d'architecture traditionnelle, de ruelles pittoresques et de patrimoine historique",
        photo2: "../ressources-map/sfax/beb-bhar.jpg",
        photo2_title:"Beb Bhar",
        photo2_subtitle:"Histoire",
        photo2_description:"Explorez Beb Bhar à Sfax, un quartier qui résonne avec l'histoire maritime et le charme méditerranéen. Situé au cœur de la médina de Sfax, Beb Bhar offre une immersion captivante dans le patrimoine de la ville",
        photo3: "../ressources-map/sfax/medina.jpg",
        photo3_title:"Medina",
        photo3_subtitle:"Histoire",
        photo3_description:"Explorez la médina de Sfax, un trésor historique qui témoigne de l'essence même de cette ville tunisienne. Nichée derrière ses remparts imposants, la médina de Sfax est un labyrinthe fascinant de ruelles, de marchés animés et de bâtiments traditionnels",
        lien_youtube:"https://www.youtube.com/embed/qjqzsjezxUY?si=A4QSwMzPt1qG7ryO",
        map_title:"Explorez Sfax à travers notre carte ",
        map_src:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d104888.4855404676!2d10.650696851572846!3d34.761507777595384!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x13002cda1486c695%3A0x22dfe0a62c50ce6f!2sSfax!5e0!3m2!1sfr!2stn!4v1706295337314!5m2!1sfr!2stn",
        back1:"../ressources-map/sfax/sfax1.png",
        back2:"../ressources-map/sfax/sfax2.png"
    },
    {
        nom:"Sidi Bouzid",
        description:"Sidi Bouzid, le berceau de l'histoire et de la résilience au cœur de la Tunisie. Entourée de vastes plaines agricoles, cette ville évoque la force de sa communauté et la persévérance qui a marqué son passé",
        titre:"Ou aller à Sidi Bouzid",
        description2:"Dans notre exploration de la magnifique région de Sidi Bouzid, nous sommes impatients de vous présenter une sélection soigneusement choisie d'endroits exceptionnels à visiter",
        photo1 :"../ressources-map/sidi-bouzid/birali-caves.jpg",
        photo1_title:"Les caves de Bir Ali",
        photo1_subtitle:"Histoire",
        photo1_description:"Explorez les Grottes de Bir Ali à Sidi Bouzid, un site naturel fascinant qui dévoile la richesse géologique de la région. Nichées au cœur du paysage désertique, ces grottes offrent une escapade intrigante pour les amateurs d'aventure et de découverte",
        photo2: "../ressources-map/sidi-bouzid/jebel-park.jpg",
        photo2_title:"Park de la montagne",
        photo2_subtitle:"Nature",
        photo2_description:" Découvrez le Parc Jbel à Sidi Bouzid, une oasis naturelle qui offre un refuge paisible au cœur de la région. Ce parc, niché au pied des montagnes, est un havre de verdure où la nature règne en maître",
        photo3: "../ressources-map/sidi-bouzid/parc-bouhdma.jpg",
        photo3_title:"Bouhedma",
        photo3_subtitle:"Nature",
        photo3_description:"Explorez Bouhedma à Sidi Bouzid, une région qui incarne la beauté naturelle et la vie rurale authentique de la Tunisie. Entourée de paysages pittoresques, Bouhedma offre des vues étendues sur des champs fertiles, des vergers verdoyants et des collines ondulantes",
        lien_youtube:"https://www.youtube.com/embed/sTodlB2NSxo?si=IQcVSZdIUEx7ACh3",
        map_title:"Explorez Sidi Bouzid à travers notre carte ",
        map_src:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d26134.49915703458!2d9.456438070776217!3d35.03642294829343!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12fec340b61767fd%3A0xcc600169ded4578c!2sSidi%20Bouzid!5e0!3m2!1sfr!2stn!4v1706295830642!5m2!1sfr!2stn",
        back1:"../ressources-map/sidi-bouzid/sidibouzid1.png",  
        back2:"../ressources-map/sidi-bouzid/sidibouzid2.png",  
    },
    {
        nom:"Siliana",
        description:"Siliana, une enclave tunisienne entre collines verdoyantes et horizons sereins. Les ruelles pittoresques de la médina dévoilent un charme authentique, tandis que les oliveraies environnantes ajoutent une touche paisible à cette ville",
        titre:"Ou aller à Siliana",
        description2:"Dans notre exploration de la magnifique région de Siliana, nous sommes impatients de vous présenter une sélection soigneusement choisie d'endroits exceptionnels à visiter",
        photo1 :"../ressources-map/siliana/ain-dhab.jpg",
        photo1_title:"Ain Dhab",
        photo1_subtitle:"Nature",
        photo1_description:"Explorez Ain Dhab à Siliana, un joyau niché au cœur de la nature tunisienne, qui séduit par sa beauté paisible et son environnement préservé. Cette oasis tranquille offre une échappée où les eaux cristallines et les paysages verdoyants créent une atmosphère apaisante",
        photo2: "../ressources-map/siliana/kesra.jpg",
        photo2_title:"Kesra",
        photo2_subtitle:"Nature",
        photo2_description:" Découvrez Kesra à Siliana, une perle nichée dans les montagnes du nord de la Tunisie, qui séduit par son atmosphère paisible et son charme montagnard. Ce village berbère, perché à flanc de colline, offre des panoramas spectaculaires sur les montagnes environnantes",
        photo3: "../ressources-map/siliana/maktaris.jpg",
        photo3_title:"Maktaris",
        photo3_subtitle:"Nature",
        photo3_description:"Explorez Maktaris à Siliana, une localité tunisienne qui séduit par son charme rural et son environnement naturel préservé. Située au cœur de la région de Siliana, Maktaris offre une immersion authentique dans la vie quotidienne de la campagne tunisienne",
        lien_youtube:"https://www.youtube.com/embed/nhWYQiiA_vU?si=hCixiD0bMFoJm_Lb",
        map_title:"Explorez Siliana à travers notre carte ",
        map_src:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d25794.1821812258!2d9.344644273891484!3d36.086838168754106!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12fc654a8737e17f%3A0xdd533dfbcc5e23ef!2sSiliana!5e0!3m2!1sfr!2stn!4v1706296193571!5m2!1sfr!2stn",
        back1:"../ressources-map/siliana/siliana1.png",
        back2:"../ressources-map/siliana/siliana2.png"  
    },
    {
        nom:"Sousse",
        description:" Sousse, joyau méditerranéen où l'histoire ancienne se marie à l'éclat balnéaire. Les remparts imposants de la médina résonnent d'échos du passé, tandis que les plages dorées et les eaux cristallines captivent les visiteurs",
        titre:"Ou aller à Sousse",
        description2:"Dans notre exploration de la magnifique région de Sousse, nous sommes impatients de vous présenter une sélection soigneusement choisie d'endroits exceptionnels à visiter",
        photo1 :"../ressources-map/sousse/hergla.jpg",
        photo1_title:"Hergla",
        photo1_subtitle:"Nature",
        photo1_description:"Découvrez Hergla à Sousse, une perle méditerranéenne qui allie charme côtier, histoire ancienne et ambiance paisible. Située le long de la côte tunisienne, Hergla séduit par ses plages de sable doré, ses eaux cristallines et son atmosphère détendue",
        photo2: "../ressources-map/sousse/kantaoui.jpg",
        photo2_title:"Kantaoui",
        photo2_subtitle:"loisirs",
        photo2_description:" Explorez Port El Kantaoui à Sousse, une station balnéaire méditerranéenne qui allie luxe, détente et plaisirs maritimes. Cette enclave côtière, conçue comme une station touristique intégrée, offre une expérience balnéaire sophistiquée sur la côte tunisienne",
        photo3: "../ressources-map/sousse/medina.jpg",
        photo3_title:"Medina",
        photo3_subtitle:"Histoire",
        photo3_description:"Explorez la médina de Sousse, un trésor historique et culturel qui dévoile la richesse de l'histoire tunisienne. Cette médina, classée au patrimoine mondial de l'UNESCO, offre une immersion captivante dans le passé de la région",
        lien_youtube:"https://www.youtube.com/embed/AITQLaR63TY?si=ARSh46hk8AVpSa1G",
        map_title:"Explorez Sousse à travers notre carte ",
        map_src:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d36090.26966227852!2d10.584267795424914!3d35.83699739557629!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x130275759ac9d10d%3A0x698e3915682cef7d!2sSousse!5e0!3m2!1sfr!2stn!4v1706296641167!5m2!1sfr!2stn",
        back1:"../ressources-map/sousse/sousse1.png",
        back2:"../ressources-map/sousse/sousse2.png"   
    },
    {
        nom:"Tataouine",
        description:"Tataouine, une oasis mystique du sud tunisien, où les paysages désertiques et les ksour traditionnels créent une toile envoûtante. Les maisons troglodytiques, nichées dans les collines, témoignent d'une architecture unique, tandis que les dunes ondulantes du Sahara ajoutent une majesté naturelle à cette région",
        titre:"Ou aller à Tataouine",
        description2:"Dans notre exploration de la magnifique région de Tataouine, nous sommes impatients de vous présenter une sélection soigneusement choisie d'endroits exceptionnels à visiter",
        photo1 :"../ressources-map/tataouine/chenini.jpg",
        photo1_title:"Chenini",
        photo1_subtitle:"Histoire",
        photo1_description:"Découvrez Chenini à Tataouine, un village berbère perché au sommet des collines du sud de la Tunisie, offrant un mélange captivant d'histoire ancienne et de charme pittoresque. Chenini se distingue par son architecture troglodyte unique, où les maisons sont creusées dans les falaises rocheuses, créant un paysage enchanteur",
        photo2: "../ressources-map/tataouine/douiret.jpg",
        photo2_title:"Douiret",
        photo2_subtitle:"Histoire",
        photo2_description:"Explorez Douiret à Tataouine, un village berbère au cœur des montagnes du sud de la Tunisie, imprégné d'histoire et de traditions ancestrales. Douiret se distingue par son architecture troglodyte, avec des maisons creusées dans les collines rocheuses, créant un paysage captivant",
        photo3: "../ressources-map/tataouine/ksar-ouled-soltane.jpg",
        photo3_title:"Ksar Ouled Soltane",
        photo3_subtitle:"Histoire",
        photo3_description:"Explorez Ksar Ouled Soltane à Tataouine, un ksar impressionnant du sud de la Tunisie qui témoigne de l'architecture traditionnelle et du mode de vie des habitants du désert. Ce ksar, datant du XVIIe siècle, est réputé pour ses greniers collectifs en forme de tours de stockage",
        lien_youtube:"https://www.youtube.com/embed/wPukxkIFbiw?si=E9VjRQNJBLBvIIwN",
        map_title:"Explorez Tataouine à travers notre carte ",
        map_src:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d53583.96966148868!2d10.401305139373942!3d32.92464833883685!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1254b7596be92873%3A0xd94cf811d4ad762d!2sTataouine!5e0!3m2!1sfr!2stn!4v1706297072053!5m2!1sfr!2stn",
        back1:"../ressources-map/tataouine/tataouine1.png",
        back2:"../ressources-map/tataouine/tataouine2.png"    
    },
    {
        nom:"Tozeur",
        description:"Tozeur, oasis enchanteresse au cœur du désert tunisien. Entourée de palmiers-dattiers, la médina aux ruelles sinueuses offre une immersion dans l'artisanat local et l'architecture traditionnelle",
        titre:"Ou aller à Tozeur",
        description2:"Dans notre exploration de la magnifique région de Tozeur, nous sommes impatients de vous présenter une sélection soigneusement choisie d'endroits exceptionnels à visiter",
        photo1 :"../ressources-map/tozeur/chott_el_jerid.jpg",
        photo1_title:"Chot el jerid",
        photo1_subtitle:"Nature",
        photo1_description:"Explorez le Chott el Jerid à Tozeur, un lac salé emblématique du désert tunisien, qui enchante les visiteurs par sa vastitude et sa beauté austère. Ce lac salé, l'un des plus grands de Tunisie, se déploie comme un mirage scintillant, créant une toile de fond spectaculaire dans le paysage désertique",
        photo2: "../ressources-map/tozeur/oasis.jpg",
        photo2_title:"Oasis",
        photo2_subtitle:"Nature",
        photo2_description:"Explorez les oasis de Tozeur, de véritables joyaux verdoyants au cœur du désert tunisien, où la vie prospère au milieu d'une oasis luxuriante. Ces oasis, telles que l'Oasis de Nefta et l'Oasis de Tozeur, offrent une vision saisissante de la coexistence harmonieuse entre l'eau précieuse et la nature",
        photo3: "../ressources-map/tozeur/tamerza-canyon.jpg",
        photo3_title:"Canyon de Tamerza",
        photo3_subtitle:"Nature",
        photo3_description:"Découvrez le Canyon de Tamerza à Tozeur, une merveille naturelle façonnée par le temps, offrant un paysage spectaculaire au cœur du désert tunisien. Ce canyon, également connu sous le nom de Corbeille de Nefta, est le résultat de l'érosion éolienne et hydrique, créant des formations rocheuses impressionnantes",
        lien_youtube:"https://www.youtube.com/embed/pZcmextBFI0?si=545eid2UIr7UDzvF&amp;start=55",
        map_title:"Explorez Tozeur à travers notre carte ",
        map_src:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d52973.92024075413!2d8.078640800561665!3d33.91874486750998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1257c028313d134d%3A0xc48c27f26a58203!2sTozeur!5e0!3m2!1sfr!2stn!4v1706297721039!5m2!1sfr!2stn",
        back1:"../ressources-map/tozeur/tozeur1.png",
        back2:"../ressources-map/tozeur/tozeur2.png"     
    },
    {
        nom:"Tunis",
        description:"Tunis, la vibrante capitale tunisienne où l'histoire et la modernité se croisent avec élégance",
        titre:"Ou aller à Tunis",
        description2:"Dans notre exploration de la magnifique région de Tunis, nous sommes impatients de vous présenter une sélection soigneusement choisie d'endroits exceptionnels à visiter",
        photo1 :"../ressources-map/tunis/sidi-bousaid.jpg",
        photo1_title:"Sidi Bou Said",
        photo1_subtitle:"Histoire",
        photo1_description:"Explorez Sidi Bou Said à Tunis, un village côtier empreint de charme méditerranéen, où l'architecture blanche éclatante contraste avec le bleu intense du ciel et de la mer. Niché sur une colline surplombant le golfe de Tunis, Sidi Bou Said est réputé pour sa beauté pittoresque et son atmosphère enchanteresse",
        photo2: "../ressources-map/tunis/theatre.jpg",
        photo2_title:"Theatre",
        photo2_subtitle:"Loisirs",
        photo2_description:"Découvrez le Théâtre Municipal de Tunis, un lieu emblématique où la culture et les arts prennent vie au cœur de la capitale tunisienne. Fondé en 1902, ce théâtre historique incarne le patrimoine artistique de la Tunisie et offre une scène riche pour diverses représentations",
        photo3: "../ressources-map/tunis/tunis-medina.jpg",
        photo3_title:"Medina",
        photo3_subtitle:"Histoire",
        photo3_description:"Explorez la médina de Tunis, un joyau historique et culturel qui transporte les visiteurs à travers les siècles au cœur de la capitale tunisienne. Classée au patrimoine mondial de l'UNESCO, la médina de Tunis est l'un des plus grands centres historiques préservés du monde arabe",
        lien_youtube:"https://www.youtube.com/embed/MrwJz0uoERk?si=vOtTYUVFqzxMhwKJ",
        map_title:"Explorez Tunis à travers notre carte ",
        map_src:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d102239.41060509732!2d10.060876000792607!3d36.794992000374286!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12fd337f5e7ef543%3A0xd671924e714a0275!2sTunis!5e0!3m2!1sfr!2stn!4v1706298078021!5m2!1sfr!2stn",
        back1:"../ressources-map/tunis/tunis1.jpg",
        back2:"../ressources-map/tunis/tunis2.jpg"      
    },
    {
        nom:"Zaghouan",
        description:"Zaghouan, joyau tunisien niché entre les montagnes et les vallées verdoyantes. Réputée pour ses sources d'eau fraîche qui jaillissent des collines environnantes, la ville offre une atmosphère paisible et ressourçante",
        titre:"Ou aller à Zaghouan",
        description2:"Dans notre exploration de la magnifique région de Zaghouan, nous sommes impatients de vous présenter une sélection soigneusement choisie d'endroits exceptionnels à visiter",
        photo1 :"../ressources-map/zaghwen/aqueduc.jpg",
        photo1_title:"Aqueduc",
        photo1_subtitle:"Histoire",
        photo1_description:"Explorez Aquadec à Zaghouan, une destination rafraîchissante et pittoresque où l'eau cristalline et les espaces verts créent une oasis au pied des montagnes. Aquadec est réputé pour ses sources d'eau abondantes et ses jardins luxuriants, offrant une escapade tranquille au cœur de la nature tunisienne",
        photo2: "../ressources-map/zaghwen/arez.jpg",
        photo2_title:"Arez",
        photo2_subtitle:"Nature",
        photo2_description:"Découvrez Arez à Zaghouan, un village niché au cœur des montagnes tunisiennes, où l'histoire et la beauté naturelle se rencontrent pour créer une atmosphère charmante. Arez est réputé pour son architecture traditionnelle, ses ruelles pittoresques et ses vues panoramiques sur les environs montagneux",
        photo3: "../ressources-map/zaghwen/zriba.jpg",
        photo3_title:"Zriba",
        photo3_subtitle:"Nature",
        photo3_description:"Découvrez Zriba à Zaghouan, un village niché au pied des montagnes tunisiennes, offrant une évasion paisible au milieu de la nature préservée. Zriba se distingue par son atmosphère tranquille, son cadre montagneux et son patrimoine culturel riche",
        lien_youtube:"https://www.youtube.com/embed/bTJoyAVhJQU?si=lVojTJK-jH_LFaeG",
        map_title:"Explorez Zaghouan à travers notre carte ",
        map_src:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d25688.094675459917!2d10.115652524864332!3d36.4089089698524!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12fd110c5ea382cd%3A0x16f187f18150bf27!2sZaghouan!5e0!3m2!1sfr!2stn!4v1706298513416!5m2!1sfr!2stn",
        back1:"../ressources-map/zaghwen/zaghwen1.png",
        back2:"../ressources-map/zaghwen/zaghwen2.png"       
    }


]